### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by fury02** [yourkungfunogood/ic-angular-cli#1]
Error

next command **yarn start** : 

./src/app/services/actor.service.ts:2:0-95 - Error: Module not found: Error: Can't resolve 'dfx-generated/hello' in '/home/fury/ic-angular-cli-master/src/app/services'

Error: src/app/app.component.ts:18:5 - error TS2322: Type 'Observable<unknown>' is not assignable to type 'Observable<string>'.
  Type 'unknown' is not assignable to type 'string'.

18     this.greeting$ = from(this.actorService.actor.greet('developer'));
       ~~~~~~~~~~~~~~


Error: src/app/services/actor.service.ts:4:22 - error TS2307: Cannot find module 'dfx-service/hello' or its corresponding type declarations.

4 import _SERVICE from 'dfx-service/hello';
                       ~~~~~~~~~~~~~~~~~~~

Edit in project **dfx version 0.7.1**

**Comment by digitaldoggo** [comment]
You would get these errors if the Hello (backend) canister has not been built before building the client app. By running the `dfx deploy Hello` command, the canister should be built and deployed to the running dfx instance. When the canister is built, a types file gets generated based on the definition of the actor.

To support imports from the canister's generated types and values files, paths were added to the `tsconfig.json`:
```json
"paths": {
  "dfx-generated/*": [".dfx/local/canisters/hello/*"],
  "dfx-service/*": [".dfx/local/canisters/hello/*"]
}
```

Did the `dfx deploy Hello` command run successfully before attempting to build/serve the client?

**Comment by fury02** [comment]
With imports implemented, it doesn't see idlFactory. The stages are correct. I also cleaned the canisters before building.
I also tried to redo your import, but I haven’t succeeded yet.

**Comment by digitaldoggo** [comment]
Do you see the generated files in the .dfx/ directory?

Directory relative to project root:
`.dfx/local/canisters/Hello/`

You should see these files in that directory:
![image](https://user-images.githubusercontent.com/950197/121379411-fe1ef200-c911-11eb-9413-cdb701a9a056.png)

**Comment by fury02** [comment]
Yes of course. It's the same for me. I'll try to redo the import, it doesn't seem to see it. IDE WebStorm in the editor also indicates ambiguity. OK thanks.

**Comment by digitaldoggo** [comment]
I see. Using two different paths in the `tsconfig.json` that reference the same source location is definitely a hacky workaround at best. I think this should be changed, but I am not sure the appropriate solution. I was struggling with this originally.

There may be a better way to get the typings for the idlFactory and canisterId from the Hello.js file. The path for the import of `dfx-generated/hello` does not really work on its own. There is a `typings.d.ts` file that was added to declare the module as well. I don't think this is the best way to go about this either.

What led to these workarounds was the fact that the Hello.d.ts is missing some exports that are present in the Hello.js module. I think that if the `Hello.d.ts` file accounted for the `idlFactory` and `canisterId` this would not be an issue. We could then remove the typings.d.ts file altogether and keep one of the two paths defined in the `tsconfig.json`. I am wondering if there is a reason the dfinity team is not including these two lines in the generated `Hello.d.ts` types file:
```ts
export const idlFactory: any;
export const canisterId: string;
```

It seems like the type file they are generating is just slightly incomplete to define the generated module.

**Comment by digitaldoggo** [comment]
While definitely a workaround, you could add these two lines to the Hello.d.ts file after the dfx build has run:
```ts
export const idlFactory: any;
export const canisterId: string;
```

Unfortunately, the file is regenerated every time we build the canister, so we would need to do this every time. I was thinking of using an npm script for running the `dfx deploy Hello` command and then creating a small node script to append those two lines to the types file that would run as a post script. I will throw something together in a branch. It is definitely working around the root problem though.

We could raise an issue with the dfinity team regarding the missing exports from the generated types file, but I am still trying to determine the best location for this. I think I am going to write something up on the developer forums. I'll post reference links between the two.

**Comment by fury02** [comment]
OK, great. I will try tomorrow. I'll write you when everything works out

**Comment by digitaldoggo** [comment]
Check out these changes:
https://github.com/yourkungfunogood/ic-angular-cli/pull/2 -> https://github.com/yourkungfunogood/ic-angular-cli/pull/2/commits/819af40eda9beecdaed37b7882ce8e7e310530c2

I am definitely interested in other ideas.

**Comment by digitaldoggo** [comment]
I created a topic on the Dfinity Developer Forum:
https://forum.dfinity.org/t/canister-types-file-does-not-include-idlfactory-or-canisterid-exports/4998

I will see what sort of ideas we can get there. I'm pretty sure there are folks a lot smarter than myself with eyes on there.  😄

**Comment by fury02** [comment]
Hello. I managed to start.
I redid it a bit (looked at your code above)
1) Everything is case-sensitive, so the name of the canister must be capitalized
The code:
File -> actor.service.ts
```
Comment:// import {canisterId as Hello_canister_id, idlFactory as Hello_idl} from 'dfx-generated/hello';
Comment:// import _SERVICE from 'dfx-service / hello';
// @ ts-ignore
import _SERVICE, {canisterId as Hello_canister_id, idlFactory as Hello_idl} from 'dfx-service/Hello';
```
2) 
File -> app.component.ts
```
Comment:// greeting $ !: Observable <string>;
greeting $ !: Observable <any>;
```
3) 
File -> tsconfig.json
```
Comment:// "dfx-service / *": [".dfx / local / canisters / hello/ *"]
"dfx-service / *": [".dfx / local / canisters / Hello / *"] #
```

**Comment by fury02** [comment]
Close

**Comment by fury02** [comment]
You can give your contact mail. I would like to ask a couple of interesting points.
